/* 数据初始化 */
DELETE FROM T_SYSTEM_PARA;
/* 系统参数表信息初始化 */
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('CPT_ACTIVE','短信验证码有效时间','60','CPT_ACTIVE','8','短信验证码有效时间参数',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('SEC01','手机认证','0','SEC','10','用户安全等级',NOW(),NOW());
/* 用户类型 */
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('USER_TYPE01','管理员','A','USER_TYPE','8','管理员',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('USER_TYPE02','普通用户','G','USER_TYPE','8','普通用户',NOW(),NOW());
/* 用户状态 */
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('USER_STATUS01','有效','A','USER_STATUS','8','有效',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('USER_STATUS02','无效','N','USER_STATUS','8','无效',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('USER_STATUS03','锁定','C','USER_STATUS','8','锁定',NOW(),NOW());
/* 账户状态 */
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('ACC_STATUS01','有效','0','ACC_STATUS','8','有效',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('ACC_STATUS02','无效','1','ACC_STATUS','8','无效',NOW(),NOW());


INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('USER_STATUS03','冻结','C','USER_STATUS','8','冻结',NOW(),NOW());
/** 基础产品类型  **/
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('PROTYP01','新股IPO','0','PROTYP','10','新股IPO',NOW(),NOW());
/** 城市列表  **/
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('CITY001','深市','0','CITY','10','深市',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('CITY002','沪市','1','CITY','10','沪市',NOW(),NOW());
/** 银行列表  **/
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('BANK0001','工商银行','0','BANK','10','工商银行',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('BANK0002','中国银行','0','BANK','10','中国银行',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('BANK0003','建设银行','0','BANK','10','建设银行',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('BANK0004','农业银行','0','BANK','10','农业银行',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('BANK0005','浦发银行','0','BANK','10','浦发银行',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('BANK0006','招商银行','0','BANK','10','招商银行',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('BANK0007','北京银行','0','BANK','10','北京银行',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('BANK0008','邮储银行','0','BANK','10','邮储银行',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('BANK0009','交通银行','0','BANK','10','交通银行',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('BANK0010','光大银行','0','BANK','10','光大银行',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('BANK0011','民生银行','0','BANK','10','民生银行',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('BANK0012','兴业银行','0','BANK','10','兴业银行',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('BANK0013','中信银行','0','BANK','10','中信银行',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('BANK0014','平安银行','0','BANK','10','平安银行',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('BANK0015','广发银行','0','BANK','10','广发银行',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('BANK0016','华夏银行','0','BANK','10','华夏银行',NOW(),NOW());

/* 产品投资类型 */
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('INVESTTYP01','全部','0','INVESTTYP','10','全部',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('INVESTTYP02','固定金额','1','INVESTTYP','10','固定金额',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('INVESTTYP03','不固定金额','2','INVESTTYP','10','不固定金额',NOW(),NOW());
/* 投资人管理费计提方式 */
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('ACCCHARGETYP01','按比例','0','ACCCHARGETYP','10','按比例',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('ACCCHARGETYP02','按金额','1','ACCCHARGETYP','10','按金额',NOW(),NOW());
/* 产品状态 */
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('INVESTPRTSTATUS01','可投资','0','INVESTPRTSTATUS','10','可投资',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('INVESTPRTSTATUS03','已开签','3','INVESTPRTSTATUS','10','已开签',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('INVESTPRTSTATUS04','已结算','2','INVESTPRTSTATUS','10','已结算',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('INVESTPRTSTATUS05','利润分配中','4','INVESTPRTSTATUS','10','利润分配中',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('INVESTPRTSTATUS06','利润分配完成','5','INVESTPRTSTATUS','10','利润分配完成',NOW(),NOW());


/* 结算状态 */
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('SETTLESTATUS01','未完成','0','SETTLESTATUS','10','利润分配未完成',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('SETTLESTATUS02','已完成','1','SETTLESTATUS','10','利润分配已完成',NOW(),NOW());
/* 账户类别*/
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('ACCTYP01','现金账户','C','ACCTYP','10','现金账户',NOW(),NOW());

/* 账户状态*/
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('ACCSTATUS01','有效','0','ACCSTATUS','10','有效',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('ACCSTATUS02','冻结','1','ACCSTATUS','10','冻结',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('ACCSTATUS03','无效','2','ACCSTATUS','10','无效',NOW(),NOW());
/* 投资状态*/
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('INVESTSTATUS01','暂存','0','INVESTSTATUS','10','暂存',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('INVESTSTATUS02','待付款','1','INVESTSTATUS','10','待付款',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('INVESTSTATUS03','投资成功','2','INVESTSTATUS','10','投资成功',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('INVESTSTATUS04','结算完成','3','INVESTSTATUS','10','结算完成',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('INVESTSTATUS05','利润分配完成','4','INVESTSTATUS','10','利润分配完成',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('INVESTSTATUS06','已删除','9','INVESTSTATUS','10','已删除',NOW(),NOW());
/* 交易类型 */
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('OPTTYP01','登录','0','OPTTYP','10','登录',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('OPTTYP03','购买','1','OPTTYP','10','购买',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('OPTTYP04','充值','2','OPTTYP','10','充值',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('OPTTYP05','提现','3','OPTTYP','10','提现',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('OPTTYP06','结算保证金','4','OPTTYP','10','结算保证金',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('OPTTYP07','结算管理费','5','OPTTYP','10','结算管理费',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('OPTTYP08','结算实得利润','6','OPTTYP','10','结算实得利润',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('OPTTYP09','结算应得利润','7','OPTTYP','10','结算应得利润',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('OPTTYP10','冲正','99','OPTTYP','10','冲正',NOW(),NOW());
/* 收付方式 */
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('PAYTYP01','付款','0','PAYTYP','10','付款',NOW(),NOW());
INSERT INTO T_SYSTEM_PARA
(PARA_CODE,PARA_NAME,PARA_VALUES,PARA_TYPE,PARA_LENGTH,REMARK,CREATE_DATE,UPDATE_DATE)
VALUES('PAYTYP02','收款','1','PAYTYP','10','收款',NOW(),NOW());
/* 平台管理员账户 */
INSERT INTO T_USER(USER_ID,USER_STATUS,USER_TYPE,PHONE,CREATE_DATE,UPDATE_DATE) VALUES(0,'A','A','13800138000',NOW(),NOW());
INSERT INTO T_SECTY_CTL(USER_ID,LOGIN_PWD,USER_STATUS,CREATE_DATE,UPDATE_DATE) VALUES(0,'111111','A',NOW(),NOW());
INSERT INTO T_ACCOUNT(USER_ID,ACC_TYPE,ACC_STATUS,ACC_BALANCE,ACC_FREEZE,ACC_ENCHASH,CREATE_DATE,UPDATE_DATE) VALUES(0,'C','0',0,0,0,NOW(),NOW());
/* 测试账户 */
INSERT INTO T_USER(USER_ID,USER_STATUS,USER_TYPE,PHONE,CREATE_DATE,UPDATE_DATE) VALUES(1,'A','A','13426179062',NOW(),NOW());
INSERT INTO T_SECTY_CTL(USER_ID,LOGIN_PWD,USER_STATUS,CREATE_DATE,UPDATE_DATE) VALUES(1,'111111','A',NOW(),NOW());
INSERT INTO T_ACCOUNT(USER_ID,ACC_TYPE,ACC_STATUS,ACC_BALANCE,ACC_FREEZE,ACC_ENCHASH,CREATE_DATE,UPDATE_DATE) VALUES(1,'C','0',0,0,0,NOW(),NOW());
INSERT INTO T_USER(USER_ID,USER_STATUS,USER_TYPE,PHONE,CREATE_DATE,UPDATE_DATE) VALUES(2,'A','A','13426179063',NOW(),NOW());
INSERT INTO T_SECTY_CTL(USER_ID,LOGIN_PWD,USER_STATUS,CREATE_DATE,UPDATE_DATE) VALUES(2,'111111','A',NOW(),NOW());
INSERT INTO T_ACCOUNT(USER_ID,ACC_TYPE,ACC_STATUS,ACC_BALANCE,ACC_FREEZE,ACC_ENCHASH,CREATE_DATE,UPDATE_DATE) VALUES(2,'C','0',0,0,0,NOW(),NOW());
/* 信息码表 0代表提示信息 1代表错误信息 */
DELETE FROM T_MSG_INFO;
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('ERR0001','0','原登录密码输入错误');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('ERR0002','0','原交易密码输入错误');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('ERR0003','0','无效验证码');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('ERR0004','0','验证码已失效，请重新生成');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('ERR0005','0','输入项错误');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('ERR0006','0','该手机号码已经注册');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('ERR0007','0','用户名或密码不正确');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('ERR0008','0','密码输入错误，连续错误5次，您的账户将被锁定');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('ERR0009','0','账户无效，请联系管理员');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('ERR0010','0','账户冻结，请联系管理员');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('ERR0011','0','您的账户已经被冻结');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('ERR0012','0','投资失败，请保持时间同步');

INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('MSG0001','0','登录密码修改成功');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('MSG0002','0','交易密码设置成功');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('MSG0003','0','交易密码修改成功');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('MSG0004','0','请先维护真实姓名');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('MSG0005','0','银行信息添加成功');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('MSG0006','0','银行信息修改成功');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('MSG0007','0','银行信息删除成功');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('MSG0008','0','用户信息修改成功');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('MSG0009','0','登录成功');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('MSG0010','0','添加基础标的成功');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('MSG0011','0','修改基础标的成功');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('MSG0012','0','删除基础标的成功');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('MSG0013','0','发行成功，该产品为可投资状态');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('MSG0014','0','删除产品成功');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('MSG0015','0','修改产品成功');
INSERT INTO T_MSG_INFO(MSG_CODE,MSG_TYP,MSG_COMMENT) VALUES('MSG0016','0','请设置新登录密码');